apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: device-fingerprint-vol
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
