apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: domain-data
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
