apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: domain-experiments
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
