apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: domain-dev
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 24Gi
