apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wangdong-s-miner-vol
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Gi
