apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-tess-code
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 684Gi
