apiVersion: batch/v1
kind: Job
metadata:
  name: wangdong-snr-v1-4
spec:
  template:
    spec:

      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             # - key: kubernetes.io/hostname
      #             #   operator: NotIn
      #             #   values:
      #             #     - perfsonar.csusb.edu
      #             #     - prp-gpu-3.t2.ucsd.edu
      #             - key: nvidia.com/gpu.product
      #               operator: In
      #               values:
      #               # - NVIDIA-TITAN-RTX
      #               - NVIDIA-A40
      #               # - NVIDIA-GeForce-RTX-2080-Ti
      #               # - NVIDIA-GeForce-RTX-1080-Ti
      #               # - NVIDIA-GeForce-RTX-3090
      #               # - NVIDIA-RTX-A6000
      #               # - NVIDIA-RTX-A5000
                      # - NVIDIA-A10
      containers:
      - name: demo
        image: xwd0418/dl_docker:optuna_plt
        command: ["/bin/bash"]
        # /data/scripts/init.sh; 
        args: 
        - "-c"
        - >-
          cd /root/ &&
          python main.py SNR/v1 
        volumeMounts:
          # - mountPath: "/data"
          #   name: wangdong-smart-vol
          - mountPath: "/root"  
            name: device-fingerprint-vol
          - mountPath: /dev/shm
            name: dshm    
        resources:
          limits:
            memory: 128Gi
            cpu: "64"
            nvidia.com/gpu: "1"
          requests:
            memory: 128Gi
            cpu: "64"
            nvidia.com/gpu: "1"
      volumes:
        - name: device-fingerprint-vol
          persistentVolumeClaim:
            claimName: device-fingerprint-vol
       
        - name: dshm
          emptyDir:
            medium: Memory
      restartPolicy: Never
      imagePullSecrets:
        - name: gitlab-auth
  backoffLimit: 4