apiVersion: batch/v1
kind: Job
metadata:
  name: tess-script
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - perfsonar.csusb.edu
                      - prp-gpu-3.t2.ucsd.edu
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                    - NVIDIA-TITAN-RTX
                    - NVIDIA-A40
                    - NVIDIA-GeForce-RTX-2080-Ti
                    - NVIDIA-GeForce-RTX-1080-Ti
                    
                  #   # - NVIDIA-A100-PCIE-40GB-MIG-2g.10gb
                    
      containers:
      - name: demo
        image: xwd0418/dl_docker:vision
        command: ["/bin/bash"]
        # /data/scripts/init.sh; 
        args: 
        - "-c"
        - >- 
          cd /root/tessellation_project &&
          ./run.sh
        volumeMounts:
          # - mountPath: "/data"
          #   name: wangdong-smart-vol
          - mountPath: "/root"
            name: smart-tess-code
          - mountPath: /dev/shm
            name: dshm    
        resources:
          limits:
            memory: 24Gi
            cpu: "4"
            nvidia.com/gpu: "2"
          requests:
            memory: 24Gi
            cpu: "4"
            nvidia.com/gpu: "2"
      volumes:
        # - name: wangdong-smart-vol
        #   persistentVolumeClaim:
        #     claimName: wangdong-smart-vol
        - name: smart-tess-code
          persistentVolumeClaim:
            claimName: smart-tess-code
        - name: dshm
          emptyDir:
            medium: Memory
      restartPolicy: Never
      imagePullSecrets:
        - name: gitlab-auth
  backoffLimit: 8