apiVersion: v1
kind: Pod
metadata:
  name: hsqc
spec:


  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: nvidia.com/gpu.product
  #               operator: In
  #               values:
  #                 # - NVIDIA-GeForce-RTX-1080
  #                 # - NVIDIA-GeForce-RTX-1080-Ti
  #                 # - NVIDIA-GeForce-RTX-2080-Ti
  #                 - NVIDIA-TITAN-RTX
  #                 - NVIDIA-A40
  #                 - NVIDIA-GeForce-RTX-3090
  #                 - NVIDIA-RTX-A6000
  #                 - NVIDIA-RTX-A5000
  #                 - NVIDIA-A10
  #                 - NVIDIA-GeForce-RTX-4090

  initContainers:
    - name: unzip-init
      image: gitlab-registry.nrp-nautilus.io/w6xu/guru-docker-image:3699f97c
      command: ["sh"]
      args:
        - "-c"
        - >-
          bash /root/gurusmart/MorganFP_prediction/task_scripts/unzip_dataset_v2.sh &&
          echo "Unzipping complete."
      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "4Gi"
          cpu: "2"
      volumeMounts:
        - mountPath: "/root"
          name: xwd-vscode
        - mountPath: "/root/gurusmart"
          name: smart-tess-code
        - mountPath: "/workspace"
          name: data-unzip

  containers:
    - name: pod-container
      image: gitlab-registry.nrp-nautilus.io/w6xu/guru-docker-image:3699f97c
      command: ["sh"]
      args: 
      - "-c"
      - >- 
        sleep infinity 
      volumeMounts:
        - mountPath: "/root"
          name: xwd-vscode
        - mountPath: "/root/gurusmart"
          name: smart-tess-code
        - mountPath: "/workspace"
          name: data-unzip
        - mountPath: /dev/shm
          name: dshm
        
      resources:
        limits:
          memory: 24Gi
          cpu: 8
          nvidia.com/gpu: 1
          ephemeral-storage: 200Gi
        requests:
          memory: 24Gi
          cpu: 8
          nvidia.com/gpu: 1
          ephemeral-storage: 200Gi
  
  volumes:
    - name: smart-tess-code
      persistentVolumeClaim:
        claimName: smart-tess-code
    - name: xwd-vscode
      persistentVolumeClaim:
        claimName: xwd-vscode
    - name: dshm
      emptyDir:
        medium: Memory
    - name: data-unzip
      emptyDir: {}
