apiVersion: v1
kind: Pod
metadata:
  name: hsqc-cp
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-1080
                  - NVIDIA-GeForce-RTX-1080-Ti
                  - NVIDIA-GeForce-RTX-2080-Ti
                  # - NVIDIA-A100-PCIE-40GB-MIG-2g.20gb
                  # - NVIDIA-A40
                  - NVIDIA-TITAN-RTX
                  - NVIDIA-A10
                # - NVIDIA-GeForce-RTX-3090
  containers:
    - name: pod-container
      image: xwd0418/dl_docker:pytorch-tensorboard
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
        
        - mountPath: /dev/shm
          name: dshm
      resources:
        limits:
          memory: 12Gi
          nvidia.com/gpu: 0
        requests:
          memory: 12Gi
          nvidia.com/gpu: 0
  volumes:
    
    - name: dshm
      emptyDir:
        medium: Memory
  # imagePullSecrets:
  #   - name: gitlab-auth
