apiVersion: v1
kind: Pod
metadata:
  name: domain-dev-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-west

          # - key: nvidia.com/gpu.product
          #   operator: In
          #   values:
          #   # - NVIDIA-GeForce-RTX-1080-Ti
          #   # - NVIDIA-GeForce-RTX-2080-Ti
          #   # - NVIDIA-A100-PCIE-40GB-MIG-2g.10gb
          #   - NVIDIA-A40
          #   - NVIDIA-TITAN-RTX
          # #   - NVIDIA-GeForce-RTX-3090
  containers:
  - name: pod-container
    image: xwd0418/dl_docker:vision
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
      - mountPath: "/root/dataset"
        name: domain-data
      - mountPath: "/root"
        name: domain-dev
      - mountPath: /dev/shm
        name: dshm    
    resources:
      limits:
        memory: 12Gi
        nvidia.com/gpu: 1
      requests:
        memory: 12Gi
        nvidia.com/gpu: 1
  volumes:
    - name: domain-data
      persistentVolumeClaim:
        claimName: domain-data
    - name: domain-dev
      persistentVolumeClaim:
        claimName: domain-dev
    - name: dshm
      emptyDir:
        medium: Memory
  imagePullSecrets:
    - name: gitlab-auth



