apiVersion: v1
kind: Pod
metadata:
  name: j-pod-smart
  namespace: guru-research
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - perfsonar.csusb.edu
                  - ry-gpu-14.sdsc.optiputer.net
  containers:
    - name: demo
      image: jamesjzhao01/smart:latest
      command: ["/bin/bash"]
      # /data/scripts/init.sh;
      args:
        - "-c"
        - >- 
          sleep infinity
      volumeMounts:
        - name: james-shared
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      resources:
        limits:
          memory: 12Gi
          cpu: "2"
          nvidia.com/gpu: "1"
        requests:
          memory: 12Gi
          cpu: "2"
          nvidia.com/gpu: "1"
      env:
        - name: PAT
          value: $env:PAT
  volumes:
    - name: james-shared
      persistentVolumeClaim:
        claimName: james-shared
    - name: dshm
      emptyDir:
        medium: Memory