apiVersion: v1
kind: Pod
metadata:
  name: domain-pod
  namespace: mc-lab
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-west

          # - key: nvidia.com/gpu.product
          #   operator: In
          #   values:
          #   - NVIDIA-A40
          #   - NVIDIA-TITAN-RTX
          #   - NVIDIA-GeForce-RTX-3090
  containers:
  - name: pod-container
    image: xwd0418/dl_docker:latest
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
      - mountPath: "/home/wangdong"
        name: smart-transformer
      - mountPath: "/data"
        name: wangdong-smart-vol
      - mountPath: "/home/dataset"
        name: vulcan-pvc1  
      - mountPath: /dev/shm
        name: dshm  
      
    resources:
      limits:
        memory: 12Gi
        nvidia.com/gpu: 2
      requests:
        memory: 12Gi
        nvidia.com/gpu: 2
  volumes:
    - name: smart-transformer
      persistentVolumeClaim:
        claimName: smart-transformer
    - name: wangdong-smart-vol
      persistentVolumeClaim:
        claimName: wangdong-smart-vol
    - name: vulcan-pvc1
      persistentVolumeClaim:
        claimName: vulcan-pvc1
    - name: dshm
      emptyDir:
        medium: Memory
  imagePullSecrets:
    - name: gitlab-auth



