apiVersion: v1
kind: Pod
metadata:
  name: ae-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-west

          # - key: nvidia.com/gpu.product
          #   operator: In
          #   values:
          #   - NVIDIA-A40
          #   - NVIDIA-TITAN-RTX
          #   - NVIDIA-GeForce-RTX-3090
  containers:
  - name: pod-container
    image: xwd0418/dl_docker:vision
    workingDir: /home/wangdong/autoencoder_denoiser/
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
      - mountPath: "/home/wangdong"
        name: ae-denoiser
      - mountPath: /dev/shm
        name: dshm    
    resources:
      limits:
        memory: 12Gi
        nvidia.com/gpu: 0
      requests:
        memory: 12Gi
        nvidia.com/gpu: 0
  volumes:
    - name: ae-denoiser
      persistentVolumeClaim:
        claimName: ae-denoiser
    - name: dshm
      emptyDir:
        medium: Memory
  imagePullSecrets:
    - name: gitlab-auth



