apiVersion: v1
kind: Pod
metadata:
  name: wangdong-s-miner
spec:

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:

          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-1080
            - NVIDIA-GeForce-RTX-1080-Ti
            - NVIDIA-GeForce-RTX-2080-Ti
            # - NVIDIA-A100-PCIE-40GB-MIG-2g.20gb
            - NVIDIA-A40
            - NVIDIA-TITAN-RTX
            - NVIDIA-GeForce-RTX-3090
            
  containers:
  - name: pod-container
    image: xwd0418/dl_docker:optuna_plt
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
      - mountPath: "/root"
        name: smart-tess-code
      - mountPath: /dev/shm
        name: dshm    
    resources:
      limits:
        memory: 16Gi
        nvidia.com/gpu: 2
        cpu: "16"
      requests:
        memory: 12Gi
        nvidia.com/gpu: 2
        cpu: "8"
  volumes:
    - name: smart-tess-code
      persistentVolumeClaim:
        claimName: smart-tess-code
    - name: dshm
      emptyDir:
        medium: Memory
  imagePullSecrets:
    - name: gitlab-auth



